spring:
  profiles:
    active: local

---
spring:
  profiles: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://123.25.30.53:3307/face_attendance
#    url: jdbc:mariadb://localhost:3306/face_attendance
    username: abis
    password: BioAdmin123!
#    password: BioAdmin123
    platform: mariadb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  h2:
    console:
      enabled: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    ROOT: info
    vn.bzcom.abis: debug

# files storage location (stores all files uploaded via REST API)
storage:
  location: ./uploads

# properties for ErrorController
server:
  error:
    whitelabel:
      enabled: true
    include-stacktrace: always

